/**
 * /archetype — embed the canonical archetype OG image from the web app.
 *
 * Zero new server work. The image is generated by `app/archetype/[slug]/
 * opengraph-image.tsx` and cached by Vercel's edge.
 *
 * Autocomplete suggests up to 25 matching slugs as the user types.
 */
import {
  AutocompleteInteraction,
  ChatInputCommandInteraction,
  SlashCommandBuilder,
} from 'discord.js';
import { ARCHETYPE_SLUGS, isValidSlug, slugToTitle } from '../archetypeSlugs.js';
import { brandedEmbed } from '../embed.js';

const WEB_URL = process.env.INVENTORY_FULL_URL || 'https://inventoryfull.gg';

export const data = new SlashCommandBuilder()
  .setName('archetype')
  .setDescription('Show an Inventory Full archetype card.')
  .addStringOption((opt) =>
    opt
      .setName('which')
      .setDescription('Type to search (40 archetypes available).')
      .setRequired(true)
      .setAutocomplete(true),
  );

export async function execute(interaction: ChatInputCommandInteraction) {
  const slug = interaction.options.getString('which', true).trim().toLowerCase();

  if (!isValidSlug(slug)) {
    await interaction.reply({
      content: `Not a known archetype. Try ${ARCHETYPE_SLUGS.slice(0, 5).map((s) => `\`${s}\``).join(', ')} — there are 40.`,
      ephemeral: true,
    });
    return;
  }

  const title = slugToTitle(slug);
  const ogUrl = `${WEB_URL}/archetype/${slug}/opengraph-image`;
  const pageUrl = `${WEB_URL}/archetype/${slug}`;

  const embed = brandedEmbed()
    .setTitle(title)
    .setURL(pageUrl)
    .setImage(ogUrl);

  await interaction.reply({ embeds: [embed] });
}

export async function autocomplete(interaction: AutocompleteInteraction) {
  const focused = interaction.options.getFocused().toLowerCase();
  const matches = ARCHETYPE_SLUGS.filter((s) => s.includes(focused) || slugToTitle(s).toLowerCase().includes(focused))
    .slice(0, 25)
    .map((s) => ({ name: slugToTitle(s), value: s }));
  await interaction.respond(matches);
}
