// Auto-generated from bot/data/pick-pool.json (344 entries)
// Maps game titles to curated mood tags for the web app picker.
// brain-off (bot) -> brainless (web app)
import type { MoodTag } from './types';

export const CURATED_MOODS: Record<string, MoodTag[]> = {
  'Hades': ['intense', 'atmospheric', 'story-rich'],
  'A Short Hike': ['chill', 'atmospheric', 'creative'],
  'Stardew Valley': ['chill', 'story-rich', 'creative'],
  'Outer Wilds': ['atmospheric', 'story-rich', 'creative'],
  'Hollow Knight': ['intense', 'atmospheric'],
  'Celeste': ['intense', 'emotional', 'story-rich'],
  'Disco Elysium': ['story-rich', 'atmospheric', 'brainless'],
  'Vampire Survivors': ['brainless', 'intense'],
  'Slay the Spire': ['strategic', 'brainless'],
  'Inscryption': ['spooky', 'story-rich', 'strategic'],
  'Slime Rancher 2': ['chill', 'brainless', 'creative'],
  'Tunic': ['atmospheric', 'strategic', 'creative'],
  'Cult of the Lamb': ['intense', 'spooky', 'strategic'],
  'Chained Echoes': ['story-rich', 'strategic'],
  'Pizza Tower': ['intense', 'brainless'],
  'Subnautica': ['spooky', 'atmospheric', 'creative'],
  'Return of the Obra Dinn': ['strategic', 'story-rich', 'atmospheric'],
  'Tetris Effect': ['chill', 'atmospheric', 'brainless'],
  'Pentiment': ['story-rich', 'atmospheric'],
  'Balatro': ['strategic', 'brainless'],
  'The Legend of Zelda: Ocarina of Time': ['story-rich', 'atmospheric', 'intense'],
  'Soulcalibur': ['intense'],
  'Super Mario Galaxy': ['intense'],
  'Metroid Prime': ['intense', 'story-rich', 'atmospheric'],
  'Super Mario Galaxy 2': ['intense'],
  'Perfect Dark': ['intense'],
  'Super Mario Odyssey': ['intense', 'brainless'],
  'The Legend of Zelda: Breath of the Wild': ['story-rich', 'atmospheric', 'intense'],
  'Baldur\'s Gate III': ['strategic', 'story-rich', 'atmospheric'],
  'The Legend of Zelda: Tears of the Kingdom': ['story-rich', 'atmospheric', 'intense'],
  'Half-Life': ['intense', 'atmospheric', 'story-rich'],
  'Uncharted 2: Among Thieves': ['intense'],
  'Red Dead Redemption 2': ['intense', 'atmospheric', 'story-rich'],
  'BioShock': ['intense', 'atmospheric', 'story-rich'],
  'Half-Life 2': ['intense', 'atmospheric', 'story-rich'],
  'Tekken 3': ['intense'],
  'Metal Gear Solid 2: Sons of Liberty': ['intense', 'atmospheric', 'strategic'],
  'The Legend of Zelda: Majora\'s Mask': ['story-rich', 'atmospheric', 'intense'],
  'Baldur\'s Gate II: Shadows of Amn': ['strategic', 'story-rich', 'atmospheric'],
  'Portal 2': ['strategic', 'story-rich', 'brainless'],
  'LittleBigPlanet': ['brainless', 'intense', 'creative'],
  'The Legend of Zelda: A Link to the Past': ['story-rich', 'atmospheric', 'intense'],
  'Grand Theft Auto IV': ['story-rich', 'atmospheric', 'intense'],
  'The Last Of Us': ['story-rich', 'atmospheric', 'intense'],
  'Red Dead Redemption': ['intense', 'atmospheric', 'story-rich'],
  'XCOM 2: War of the Chosen': ['strategic'],
  'Elden Ring': ['intense', 'story-rich', 'strategic'],
  'The Orange Box': ['intense'],
  'Burnout 3: Takedown': ['brainless', 'intense'],
  'Chrono Cross': ['story-rich', 'strategic'],
  'Resident Evil Code: Veronica': ['story-rich', 'atmospheric', 'intense'],
  'The Elder Scrolls IV: Oblivion': ['atmospheric', 'story-rich', 'strategic'],
  'Grand Theft Auto: Vice City': ['intense', 'atmospheric', 'creative'],
  'God of War I': ['intense', 'atmospheric', 'story-rich'],
  'Diablo': ['brainless', 'intense'],
  'The Elder Scrolls V: Skyrim': ['intense', 'story-rich', 'strategic'],
  'Batman: Arkham City': ['intense', 'spooky', 'atmospheric'],
  'BioShock Infinite': ['intense', 'atmospheric', 'story-rich'],
  'Divinity: Original Sin 2 - Definitive Edition': ['story-rich', 'strategic'],
  'Metal Gear Solid 3: Subsistence': ['intense'],
  'Divinity: Original Sin - Enhanced Edition': ['atmospheric', 'story-rich', 'strategic'],
  'Metal Gear Solid': ['intense'],
  'Grim Fandango': ['story-rich', 'atmospheric'],
  'Command & Conquer': ['strategic'],
  'Super Mario 64': ['intense'],
  'Metal Gear Solid 4: Guns of the Patriots': ['intense'],
  'Mass Effect 2': ['intense', 'story-rich', 'strategic'],
  'Persona 5 Royal': ['story-rich', 'atmospheric', 'strategic'],
  'Sid Meier\'s Civilization IV': ['strategic'],
  'Jet Set Radio': ['intense', 'atmospheric'],
  'God of War (2018)': ['intense', 'atmospheric', 'story-rich'],
  'StarCraft II: Wings of Liberty': ['strategic'],
  'Company of Heroes': ['strategic'],
  'Gears of War 2': ['intense'],
  'Dwarf Fortress': ['strategic', 'atmospheric', 'story-rich'],
  'Okami': ['story-rich', 'atmospheric', 'intense'],
  'Grand Theft Auto III': ['intense', 'atmospheric', 'story-rich'],
  'The Last of Us Part II': ['intense', 'story-rich', 'atmospheric'],
  'Maniac Mansion: Day of the Tentacle': ['story-rich', 'atmospheric', 'brainless'],
  'Castlevania: Symphony of the Night': ['story-rich', 'atmospheric', 'intense'],
  'SSX 3': ['brainless'],
  'Paper Mario (2000)': ['story-rich', 'strategic'],
  'Skies of Arcadia': ['story-rich', 'strategic'],
  'Grand Theft Auto: San Andreas': ['intense', 'atmospheric', 'story-rich'],
  'Super Mario 3D World': ['intense'],
  'The Legend of Zelda: Skyward Sword': ['story-rich', 'atmospheric'],
  'Homeworld': ['strategic'],
  'Super Smash Bros. Ultimate': ['intense'],
  'God of War II': ['intense'],
  'Demon\'s Souls (2020)': ['intense', 'story-rich', 'strategic'],
  'Sid Meier\'s Alpha Centauri': ['strategic'],
  'Soul Calibur II': ['intense'],
  'FINAL FANTASY VI': ['story-rich', 'strategic', 'atmospheric'],
  'The Walking Dead: Season 1': ['story-rich', 'atmospheric', 'intense'],
  'God of War III': ['intense'],
  'Uncharted 3: Drake\'s Deception': ['intense', 'atmospheric'],
  'Eternal Darkness: Sanity\'s Requiem': ['story-rich', 'atmospheric', 'intense'],
  'Vagrant Story (2000)': ['story-rich', 'atmospheric', 'intense'],
  'Mario Kart 8 Deluxe': ['brainless'],
  'Call of Duty 4: Modern Warfare': ['intense', 'atmospheric', 'story-rich'],
  'Super Mario World': ['intense', 'brainless'],
  'Metroid Fusion': ['intense'],
  'Fire Emblem Awakening': ['strategic', 'story-rich'],
  'Super Mario Sunshine': ['intense', 'story-rich', 'atmospheric'],
  'Bloodborne': ['intense', 'atmospheric', 'spooky'],
  'Undertale': ['atmospheric', 'story-rich', 'strategic'],
  'Final Fantasy X': ['story-rich', 'strategic'],
  'Tom Clancy\'s Splinter Cell Chaos Theory': ['story-rich', 'atmospheric', 'intense'],
  'Final Fantasy XII': ['story-rich', 'strategic'],
  'A Monster\'s Expedition': ['story-rich', 'atmospheric', 'brainless'],
  'Thief: The Dark Project': ['intense'],
  'Warcraft 3: Reign of Chaos': ['strategic'],
  'Braid': ['strategic', 'atmospheric'],
  'Bayonetta 2': ['intense', 'brainless'],
  'Metroid Prime 2: Echoes': ['story-rich', 'atmospheric', 'intense'],
  'Age of Empires II: Age of Kings': ['strategic'],
  'Grand Theft Auto V': ['intense', 'atmospheric', 'creative'],
  'Conker\'s Bad Fur Day': ['intense'],
  'Banjo-Kazooie': ['intense', 'story-rich', 'atmospheric'],
  'Journey': ['atmospheric', 'story-rich', 'spooky'],
  'System Shock 2': ['intense', 'story-rich', 'strategic'],
  'The Witcher 3: Wild Hunt': ['intense', 'story-rich', 'strategic'],
  'Crash Bandicoot 3: Warped': ['intense'],
  'Gears of War 3': ['intense'],
  'Tom Clancy\'s Splinter Cell': ['story-rich', 'atmospheric', 'intense'],
  'Crysis': ['intense', 'atmospheric', 'story-rich'],
  'Shadow of the Colossus': ['story-rich', 'atmospheric', 'intense'],
  'The Legend of Zelda: A Link Between Worlds': ['story-rich', 'atmospheric'],
  'Klonoa 2: Lunatea\'s Veil': ['intense', 'story-rich', 'atmospheric'],
  'Ninja Gaiden (2004)': ['intense'],
  'Super Mario World 2: Yoshi\'s Island': ['intense'],
  'Mark of the Ninja': ['intense', 'atmospheric', 'story-rich'],
  'Death Road to Canada': ['atmospheric', 'story-rich', 'intense'],
  'FEZ': ['story-rich', 'atmospheric', 'intense'],
  'Spyro: Year of the Dragon': ['intense', 'story-rich', 'atmospheric'],
  'Call of Duty': ['intense', 'atmospheric', 'story-rich'],
  'Resident Evil 2': ['story-rich', 'atmospheric', 'intense'],
  'God of War: Chains of Olympus': ['intense'],
  'Ratchet & Clank: Up Your Arsenal': ['intense'],
  'Tony Hawk\'s Pro Skater 2': ['brainless', 'intense'],
  'Deus Ex: Human Revolution - Director\'s Cut': ['intense', 'story-rich', 'strategic'],
  'Castlevania: Aria of Sorrow': ['intense'],
  'Dark Souls II': ['intense', 'story-rich', 'strategic'],
  'Baldur\'s Gate': ['strategic', 'story-rich'],
  'Halo 3': ['intense'],
  'DRAGON QUEST XI S: Echoes of an Elusive Age - Definitive Edition': ['story-rich', 'atmospheric', 'strategic'],
  'The Longest Journey': ['story-rich', 'atmospheric', 'brainless'],
  'Rez Infinite': ['brainless', 'chill', 'atmospheric'],
  'Metal Gear Solid V: The Phantom Pain': ['intense', 'atmospheric', 'story-rich'],
  'Fallout 3': ['intense', 'story-rich', 'strategic'],
  'Planescape: Torment': ['strategic', 'story-rich', 'atmospheric'],
  'Dragon Age: Origins': ['story-rich', 'strategic', 'atmospheric'],
  'Ori and the Will of the Wisps': ['intense', 'story-rich', 'atmospheric'],
  'Resident Evil': ['intense'],
  'Golden Sun': ['story-rich', 'strategic'],
  'Tony Hawk\'s Pro Skater 4': ['brainless', 'intense'],
  'Twisted Metal: Black': ['brainless'],
  'Legacy of Kain: Soul Reaver': ['intense', 'story-rich', 'atmospheric'],
  'Dishonored': ['story-rich', 'atmospheric', 'intense'],
  'Batman: Arkham Asylum': ['intense', 'atmospheric', 'story-rich'],
  'Shovel Knight: Treasure Trove': ['intense', 'story-rich', 'atmospheric'],
  'Halo: Reach': ['intense'],
  'N++ (NPLUSPLUS)': ['intense', 'brainless'],
  'Metroid Prime 3: Corruption': ['story-rich', 'atmospheric', 'intense'],
  'Gears of War': ['intense'],
  'Grand Theft Auto: Chinatown Wars': ['story-rich', 'atmospheric', 'intense'],
  'Microsoft Flight Simulator 2020': ['chill', 'creative', 'atmospheric'],
  'Mario and Luigi: Bowser\'s Inside Story': ['story-rich', 'strategic'],
  'Tony Hawk\'s Underground': ['atmospheric'],
  'ICO': ['intense', 'atmospheric'],
  'Deus Ex': ['intense', 'story-rich', 'strategic'],
  'Banjo-Tooie': ['intense', 'story-rich', 'atmospheric'],
  'Tom Clancy\'s Splinter Cell: Pandora Tomorrow': ['story-rich', 'atmospheric', 'intense'],
  'Viewtiful Joe (2003)': ['intense'],
  'DRAGON QUEST V': ['story-rich', 'strategic'],
  'Halo: Combat Evolved': ['intense'],
  'Sea of Stars': ['story-rich', 'strategic'],
  'Total War: SHOGUN 2': ['strategic'],
  'Sekiro: Shadows Die Twice': ['intense', 'story-rich', 'strategic'],
  'Odin Sphere Leifthrasir': ['story-rich', 'strategic'],
  'Ape Escape': ['intense'],
  'Donkey Kong 64': ['intense', 'story-rich', 'atmospheric'],
  'Mario & Luigi: Superstar Saga': ['story-rich', 'strategic'],
  'The Room Three': ['atmospheric', 'story-rich', 'brainless'],
  'Bayonetta': ['story-rich', 'atmospheric', 'intense'],
  'FINAL FANTASY VIII': ['story-rich', 'strategic', 'atmospheric'],
  'Spelunky 2': ['intense', 'atmospheric', 'strategic'],
  'Brothers: A Tale of Two Sons': ['atmospheric', 'story-rich', 'intense'],
  'Mass Effect 3': ['intense', 'story-rich', 'strategic'],
  'Sid Meier\'s Civilization V': ['strategic'],
  'Into the Breach': ['strategic', 'atmospheric', 'story-rich'],
  'Diablo IV': ['brainless', 'intense'],
  'Animal Crossing: New Horizons': ['chill', 'brainless', 'creative'],
  'The Legend of Zelda: Phantom Hourglass': ['story-rich', 'atmospheric', 'intense'],
  'Forza Horizon 4': ['brainless', 'intense', 'atmospheric'],
  'Jak and Daxter: The Precursor Legacy': ['intense'],
  'Black & White': ['atmospheric', 'strategic', 'story-rich'],
  'The Witness': ['strategic', 'atmospheric', 'chill'],
  'Inside': ['atmospheric', 'spooky', 'emotional'],
  'Limbo': ['atmospheric', 'spooky'],
  'What Remains of Edith Finch': ['story-rich', 'emotional', 'atmospheric'],
  'Firewatch': ['story-rich', 'atmospheric', 'emotional'],
  'Gone Home': ['story-rich', 'emotional', 'atmospheric'],
  'Control': ['atmospheric', 'intense', 'story-rich'],
  'Psychonauts 2': ['creative', 'story-rich', 'atmospheric'],
  'Titanfall 2': ['intense', 'story-rich'],
  'Doom (2016)': ['intense', 'brainless'],
  'Doom Eternal': ['intense', 'brainless'],
  'Death Stranding': ['atmospheric', 'story-rich', 'chill'],
  'It Takes Two': ['creative', 'chill', 'emotional'],
  'Cyberpunk 2077': ['story-rich', 'intense', 'atmospheric'],
  'Horizon Zero Dawn': ['story-rich', 'atmospheric', 'intense'],
  'Ghost of Tsushima': ['atmospheric', 'intense', 'story-rich'],
  'Spiritfarer': ['chill', 'emotional', 'creative'],
  'Cocoon': ['strategic', 'atmospheric'],
  'The Talos Principle': ['strategic', 'atmospheric', 'story-rich'],
  'Prey (2017)': ['atmospheric', 'spooky', 'strategic'],
  'Dead Cells': ['intense', 'strategic'],
  'Dark Souls': ['intense', 'atmospheric'],
  'Dark Souls III': ['intense', 'atmospheric'],
  'Returnal': ['intense', 'atmospheric', 'spooky'],
  'Alan Wake 2': ['spooky', 'story-rich', 'atmospheric'],
  'Resident Evil Village': ['spooky', 'intense'],
  'Resident Evil 4 (2023)': ['intense', 'spooky'],
  'Hi-Fi Rush': ['intense', 'brainless', 'creative'],
  'Sifu': ['intense'],
  'Neon White': ['intense', 'brainless'],
  'Katana ZERO': ['intense', 'story-rich'],
  'Oxenfree': ['story-rich', 'spooky', 'atmospheric'],
  'Night in the Woods': ['story-rich', 'emotional', 'atmospheric'],
  'Hellblade: Senua\'s Sacrifice': ['atmospheric', 'emotional', 'intense'],
  'Ori and the Blind Forest': ['atmospheric', 'emotional', 'intense'],
  'Cuphead': ['intense'],
  'Final Fantasy VII Remake': ['story-rich', 'intense', 'emotional'],
  'Yakuza 0': ['story-rich', 'intense', 'brainless'],
  '13 Sentinels: Aegis Rim': ['story-rich', 'strategic', 'emotional'],
  'Little Nightmares': ['spooky', 'atmospheric'],
  'A Plague Tale: Innocence': ['story-rich', 'atmospheric', 'emotional'],
  'Transistor': ['atmospheric', 'strategic', 'story-rich'],
  'Bastion': ['atmospheric', 'intense', 'story-rich'],
  'Pyre': ['story-rich', 'atmospheric', 'strategic'],
  'The Forgotten City': ['story-rich', 'strategic', 'atmospheric'],
  'Chicory: A Colorful Tale': ['chill', 'emotional', 'creative'],
  'Stray': ['atmospheric', 'chill'],
  'Her Story': ['story-rich', 'strategic'],
  'Citizen Sleeper': ['story-rich', 'atmospheric', 'strategic'],
  'Loop Hero': ['strategic', 'brainless'],
  'Hyper Light Drifter': ['atmospheric', 'intense'],
  'CrossCode': ['story-rich', 'strategic', 'intense'],
  'Astro Bot': ['chill', 'creative'],
  'Animal Well': ['atmospheric', 'strategic', 'spooky'],
  'Outer Worlds': ['story-rich', 'strategic'],
  'Monster Hunter: World': ['intense', 'strategic', 'chill'],
  'Celeste 2: Lani\'s Trek': ['intense', 'emotional'],
  'The Pathless': ['atmospheric', 'chill'],
  'Unpacking': ['chill', 'emotional'],
  'Hades II': ['intense', 'story-rich', 'atmospheric'],
  'Clair Obscur: Expedition 33': ['story-rich', 'intense', 'atmospheric'],
  'Final Fantasy XVI': ['intense', 'story-rich', 'atmospheric'],
  'Marvel\'s Spider-Man 2': ['intense', 'story-rich'],
  'Dave the Diver': ['chill', 'creative', 'brainless'],
  'Dredge': ['atmospheric', 'spooky', 'chill'],
  'Lies of P': ['intense', 'atmospheric'],
  'Super Mario Bros. Wonder': ['chill', 'creative', 'brainless'],
  'Pikmin 4': ['strategic', 'chill', 'creative'],
  'Armored Core VI: Fires of Rubicon': ['intense', 'strategic'],
  'Black Myth: Wukong': ['intense', 'atmospheric', 'story-rich'],
  'Metaphor: ReFantazio': ['story-rich', 'strategic', 'atmospheric'],
  'Final Fantasy VII Rebirth': ['story-rich', 'emotional', 'intense'],
  'Silent Hill 2 (2024)': ['spooky', 'atmospheric', 'emotional'],
  'Like a Dragon: Infinite Wealth': ['story-rich', 'brainless', 'emotional'],
  'UFO 50': ['creative', 'strategic', 'intense'],
  'Lorelei and the Laser Eyes': ['strategic', 'atmospheric', 'spooky'],
  'Neva': ['atmospheric', 'emotional'],
  'Senua\'s Saga: Hellblade II': ['atmospheric', 'emotional', 'intense'],
  'Indiana Jones and the Great Circle': ['story-rich', 'intense', 'atmospheric'],
  'Thank Goodness You\'re Here!': ['brainless', 'chill'],
  'Marvel\'s Spider-Man: Miles Morales': ['intense', 'story-rich'],
  'Marvel\'s Spider-Man Remastered': ['intense', 'story-rich', 'brainless'],
  'Remnant II': ['intense', 'strategic'],
  'Warhammer 40,000: Space Marine 2': ['intense', 'brainless'],
  'Townscaper': ['chill', 'creative'],
  'PowerWash Simulator': ['chill', 'brainless'],
  'Katamari Damacy REROLL': ['brainless', 'chill', 'creative'],
  'Untitled Goose Game': ['brainless', 'chill', 'creative'],
  'Dorfromantik': ['chill', 'creative', 'brainless'],
  'Abzu': ['chill', 'atmospheric', 'emotional'],
  'Gris': ['atmospheric', 'emotional', 'chill'],
  'Kind Words': ['chill', 'emotional'],
  'Eastshade': ['chill', 'creative', 'atmospheric'],
  'Wylde Flowers': ['chill', 'story-rich', 'creative'],
  'The Gardens Between': ['chill', 'emotional', 'atmospheric'],
  'Soma': ['spooky', 'story-rich', 'atmospheric'],
  'Amnesia: The Dark Descent': ['spooky', 'atmospheric'],
  'Phasmophobia': ['spooky', 'brainless'],
  'Peglin': ['brainless', 'strategic'],
  'Webbed': ['chill', 'creative'],
  'Wandersong': ['chill', 'emotional', 'story-rich'],
  'Teardown': ['creative', 'brainless'],
  'Overcooked 2': ['brainless', 'intense'],
  'Trombone Champ': ['brainless', 'chill'],
  'Celeste 64: Fragments of the Mountain': ['intense'],
  'Before Your Eyes': ['emotional', 'story-rich'],
  'To the Moon': ['emotional', 'story-rich'],
  'Florence': ['emotional', 'chill'],
  'Venba': ['emotional', 'story-rich', 'chill'],
  'Baba Is You': ['strategic', 'creative'],
  'Papers, Please': ['strategic', 'emotional', 'atmospheric'],
  'Sable': ['chill', 'atmospheric', 'creative'],
  'Viewfinder': ['creative', 'atmospheric', 'chill'],
  'Resident Evil 2 (2019)': ['spooky', 'intense'],
  'Pathologic 2': ['spooky', 'atmospheric', 'story-rich'],
  'Darkest Dungeon': ['spooky', 'strategic'],
  'Elden Ring: Shadow of the Erdtree': ['intense', 'atmospheric', 'spooky'],
  'Factorio': ['creative', 'strategic'],
  'Satisfactory': ['creative', 'chill'],
  'Minecraft': ['creative', 'chill', 'brainless'],
  'Terraria': ['creative', 'intense'],
  'No Man\'s Sky': ['creative', 'atmospheric', 'chill'],
  'Rimworld': ['creative', 'strategic'],
  'Cities: Skylines': ['creative', 'strategic', 'chill'],
  'Anno 1800': ['creative', 'strategic', 'chill'],
  'Planet Zoo': ['creative', 'chill'],
  'Astroneer': ['creative', 'chill'],
  'Borderlands 3': ['brainless', 'intense'],
  'Just Cause 3': ['brainless', 'intense'],
  'The Binding of Isaac: Rebirth': ['brainless', 'intense'],
  'LEGO Star Wars: The Skywalker Saga': ['brainless', 'chill'],
  'Risk of Rain 2': ['brainless', 'intense'],
  'Far Cry 6': ['brainless', 'intense'],
  'Grim Dawn': ['brainless', 'intense', 'atmospheric'],
  'Monster Train': ['brainless', 'strategic'],
  'Brotato': ['brainless', 'intense'],
  'Assassin\'s Creed Odyssey': ['brainless', 'atmospheric'],
  'Life is Strange': ['emotional', 'story-rich'],
  'The Last Guardian': ['emotional', 'atmospheric'],
  'Omori': ['emotional', 'story-rich', 'spooky'],
  'STALKER 2: Heart of Chornobyl': ['spooky', 'atmospheric', 'intense'],
  'The Forest': ['spooky', 'creative'],
  'Alien: Isolation': ['spooky', 'atmospheric', 'intense'],
  'Project Zomboid': ['spooky', 'strategic'],
  'Dead Space (2023)': ['spooky', 'intense', 'atmospheric'],
  'Metro Exodus': ['spooky', 'atmospheric', 'story-rich'],
  'The Legend of Zelda: The Wind Waker': ['atmospheric', 'story-rich', 'chill'],
};
