import { Game } from './types';

/**
 * A pre-built sample library for users who want to explore the app
 * without importing their own games. Feels like a real person's backlog —
 * messy, aspirational, a few hours here and there.
 */

const now = new Date().toISOString();
const daysAgo = (d: number) => new Date(Date.now() - d * 86400000).toISOString();

// Deterministic IDs so they're stable across renders
let _id = 0;
const sampleId = () => `sample-${++_id}`;

export const SAMPLE_GAMES: Game[] = [
  // ── NOW PLAYING (1) — 2 slots intentionally open so users can park something here ──

  {
    id: sampleId(),
    name: 'Baldur\'s Gate 3',
    source: 'steam',
    steamAppId: 1086940,
    coverUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/1086940/header.jpg',
    metacritic: 96,
    genres: ['RPG', 'Adventure', 'Strategy'],
    hoursPlayed: 52,
    installed: true,
    timeTier: 'marathon',
    category: 'The Pile',
    vibes: ['narrative'],
    priority: 0,
    notes: 'Deep in Act 2. Karlach is the best.',
    status: 'playing',
    moodTags: ['story-rich', 'strategic'],
    description: 'Gather your party and return to the Forgotten Realms in a tale of fellowship and betrayal, sacrifice and survival.',
    hltbMain: 55,
    hltbComplete: 150,
    enrichedAt: now,
    addedAt: daysAgo(45),
    updatedAt: daysAgo(1),
  },
  {
    id: sampleId(),
    name: 'Elden Ring',
    source: 'steam',
    steamAppId: 1245620,
    coverUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/1245620/header.jpg',
    metacritic: 96,
    genres: ['Action', 'RPG', 'Adventure'],
    hoursPlayed: 38,
    installed: true,
    timeTier: 'marathon',
    category: 'The Pile',
    vibes: ['challenge', 'atmospheric'],
    priority: 1,
    notes: 'Paused in Liurnia. Died enough times, needed a break.',
    status: 'on-deck',
    moodTags: ['intense', 'atmospheric'],
    description: 'Rise, Tarnished, and be guided by grace to brandish the power of the Elden Ring.',
    hltbMain: 55,
    hltbComplete: 133,
    enrichedAt: now,
    addedAt: daysAgo(60),
    updatedAt: daysAgo(3),
  },
  {
    id: sampleId(),
    name: 'Stardew Valley',
    source: 'steam',
    steamAppId: 413150,
    coverUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/413150/header.jpg',
    metacritic: 89,
    genres: ['Simulation', 'RPG', 'Indie'],
    hoursPlayed: 84,
    installed: true,
    timeTier: 'wind-down',
    category: 'Favorites',
    vibes: ['cozy'],
    priority: 0,
    notes: 'Year 3 save still going. Drop back in whenever.',
    status: 'on-deck',
    moodTags: ['chill', 'creative'],
    description: 'You\'ve inherited your grandfather\'s old farm plot. Armed with hand-me-down tools, you set out to begin your new life.',
    hltbMain: 52,
    hltbComplete: 153,
    enrichedAt: now,
    isNonFinishable: true,
    addedAt: daysAgo(120),
    updatedAt: daysAgo(2),
  },

  // ── ON DECK (5) ─────────────────────────────────────────────────

  {
    id: sampleId(),
    name: 'Hades',
    source: 'steam',
    steamAppId: 1145360,
    coverUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/1145360/header.jpg',
    metacritic: 93,
    genres: ['Action', 'Indie', 'RPG'],
    hoursPlayed: 2,
    installed: true,
    timeTier: 'deep-cut',
    category: 'The Pile',
    vibes: ['challenge'],
    priority: 0,
    notes: 'Did one run. Died to Meg. Need to go back.',
    status: 'on-deck',
    moodTags: ['intense', 'story-rich'],
    description: 'Defy the god of the dead as you hack and slash your way out of the Underworld.',
    hltbMain: 21,
    hltbComplete: 96,
    enrichedAt: now,
    addedAt: daysAgo(30),
    updatedAt: daysAgo(10),
  },
  {
    id: sampleId(),
    name: 'Outer Wilds',
    source: 'steam',
    steamAppId: 753640,
    coverUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/753640/header.jpg',
    metacritic: 85,
    genres: ['Adventure', 'Indie'],
    hoursPlayed: 0,
    installed: true,
    timeTier: 'deep-cut',
    category: 'The Pile',
    vibes: ['atmospheric', 'philosophical'],
    priority: 1,
    notes: 'Everyone says this is life-changing. No spoilers please.',
    status: 'on-deck',
    moodTags: ['atmospheric', 'emotional'],
    description: 'Explore a solar system stuck in an endless time loop. A mystery hiding in plain sight.',
    hltbMain: 15,
    hltbComplete: 22,
    enrichedAt: now,
    addedAt: daysAgo(20),
    updatedAt: daysAgo(20),
  },
  {
    id: sampleId(),
    name: 'Disco Elysium',
    source: 'steam',
    steamAppId: 632470,
    coverUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/632470/header.jpg',
    metacritic: 91,
    genres: ['RPG', 'Adventure'],
    hoursPlayed: 0,
    installed: false,
    timeTier: 'deep-cut',
    category: 'The Pile',
    vibes: ['narrative', 'philosophical'],
    priority: 2,
    notes: '',
    status: 'on-deck',
    moodTags: ['story-rich', 'emotional', 'atmospheric'],
    description: 'A groundbreaking open-world RPG. You\'re a detective with a unique skill system at your disposal.',
    hltbMain: 24,
    hltbComplete: 46,
    enrichedAt: now,
    addedAt: daysAgo(90),
    updatedAt: daysAgo(60),
  },

  // ── COMPLETED (4) ───────────────────────────────────────────────

  {
    id: sampleId(),
    name: 'Celeste',
    source: 'steam',
    steamAppId: 504230,
    coverUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/504230/header.jpg',
    metacritic: 92,
    genres: ['Platformer', 'Indie', 'Action'],
    hoursPlayed: 14,
    installed: false,
    timeTier: 'deep-cut',
    category: 'Favorites',
    vibes: ['challenge'],
    priority: 0,
    notes: 'One of the best games I\'ve ever played.',
    status: 'played',
    rating: 5,
    completedAt: daysAgo(180),
    moodTags: ['intense', 'emotional'],
    description: 'Help Madeline survive her inner demons on her journey to the top of Celeste Mountain.',
    hltbMain: 8,
    hltbComplete: 36,
    enrichedAt: now,
    addedAt: daysAgo(300),
    updatedAt: daysAgo(180),
  },
  {
    id: sampleId(),
    name: 'The Witcher 3: Wild Hunt',
    source: 'steam',
    steamAppId: 292030,
    coverUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/292030/header.jpg',
    metacritic: 92,
    genres: ['RPG', 'Adventure', 'Action'],
    hoursPlayed: 112,
    installed: false,
    timeTier: 'marathon',
    category: 'Favorites',
    vibes: ['narrative', 'atmospheric'],
    priority: 1,
    notes: 'Main story + Hearts of Stone. Still need Blood and Wine.',
    status: 'played',
    rating: 5,
    completedAt: daysAgo(400),
    moodTags: ['story-rich', 'atmospheric'],
    description: 'You are Geralt of Rivia, mercenary monster slayer. Before you stands a war-torn, monster-infested continent.',
    hltbMain: 51,
    hltbComplete: 173,
    enrichedAt: now,
    addedAt: daysAgo(500),
    updatedAt: daysAgo(400),
  },
  {
    id: sampleId(),
    name: 'Portal 2',
    source: 'steam',
    steamAppId: 620,
    coverUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/620/header.jpg',
    metacritic: 95,
    genres: ['Puzzle', 'Action', 'Adventure'],
    hoursPlayed: 9,
    installed: false,
    timeTier: 'deep-cut',
    category: 'Favorites',
    vibes: [],
    priority: 2,
    notes: 'Perfect game. No notes.',
    status: 'played',
    rating: 5,
    completedAt: daysAgo(900),
    moodTags: ['chill', 'creative'],
    description: 'The "Perpetual Testing Initiative" has been expanded to allow portal devices to manipulate the world itself.',
    hltbMain: 8,
    hltbComplete: 23,
    enrichedAt: now,
    addedAt: daysAgo(1000),
    updatedAt: daysAgo(900),
  },
  {
    id: sampleId(),
    name: 'Inscryption',
    source: 'steam',
    steamAppId: 1092790,
    coverUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/1092790/header.jpg',
    metacritic: 86,
    genres: ['Card Game', 'Horror', 'Indie'],
    hoursPlayed: 11,
    installed: false,
    timeTier: 'deep-cut',
    category: 'The Pile',
    vibes: ['atmospheric'],
    priority: 3,
    notes: 'Whoa.',
    status: 'played',
    rating: 4,
    completedAt: daysAgo(150),
    moodTags: ['spooky', 'strategic', 'atmospheric'],
    description: 'An inky black card-based odyssey that blends the deckbuilder and escape-room genres.',
    hltbMain: 10,
    hltbComplete: 18,
    enrichedAt: now,
    addedAt: daysAgo(200),
    updatedAt: daysAgo(150),
  },

  // ── BAILED (2) ──────────────────────────────────────────────────

  {
    id: sampleId(),
    name: 'Cyberpunk 2077',
    source: 'steam',
    steamAppId: 1091500,
    coverUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/1091500/header.jpg',
    metacritic: 86,
    genres: ['RPG', 'Action', 'Adventure'],
    hoursPlayed: 12,
    installed: false,
    timeTier: 'marathon',
    category: 'The Pile',
    vibes: [],
    priority: 0,
    notes: 'Might try again post-patches. Just wasn\'t feeling it.',
    status: 'bailed',
    moodTags: ['intense', 'story-rich'],
    description: 'An open-world, action-adventure RPG set in the megalopolis of Night City.',
    hltbMain: 24,
    hltbComplete: 102,
    enrichedAt: now,
    addedAt: daysAgo(400),
    updatedAt: daysAgo(350),
  },
  {
    id: sampleId(),
    name: 'Death Stranding',
    source: 'steam',
    steamAppId: 1190460,
    coverUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/1190460/header.jpg',
    metacritic: 85,
    genres: ['Adventure', 'Action'],
    hoursPlayed: 5,
    installed: false,
    timeTier: 'marathon',
    category: 'The Pile',
    vibes: ['atmospheric'],
    priority: 1,
    notes: 'I respect what it\'s doing but I am bored.',
    status: 'bailed',
    moodTags: ['atmospheric', 'story-rich'],
    description: 'From legendary game creator Hideo Kojima comes a genre-defying experience.',
    hltbMain: 40,
    hltbComplete: 113,
    enrichedAt: now,
    addedAt: daysAgo(250),
    updatedAt: daysAgo(200),
  },

  // ── BURIED (the real backlog — bulk of the library) ──────────────

  {
    id: sampleId(),
    name: 'Red Dead Redemption 2',
    source: 'steam',
    steamAppId: 1174180,
    coverUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/1174180/header.jpg',
    metacritic: 93,
    genres: ['Adventure', 'Action'],
    hoursPlayed: 3,
    installed: false,
    timeTier: 'marathon',
    category: 'The Pile',
    vibes: ['narrative', 'atmospheric'],
    priority: 0,
    notes: 'Got through the snow tutorial. That\'s it.',
    status: 'buried',
    moodTags: ['story-rich', 'atmospheric'],
    description: 'America, 1899. Arthur Morgan and the Van der Linde gang are on the run.',
    hltbMain: 49,
    hltbComplete: 163,
    enrichedAt: now,
    addedAt: daysAgo(200),
    updatedAt: daysAgo(190),
  },
  {
    id: sampleId(),
    name: 'Hollow Knight',
    source: 'steam',
    steamAppId: 367520,
    coverUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/367520/header.jpg',
    metacritic: 87,
    genres: ['Action', 'Indie', 'Adventure'],
    hoursPlayed: 6,
    installed: true,
    timeTier: 'deep-cut',
    category: 'The Pile',
    vibes: ['atmospheric', 'challenge'],
    priority: 1,
    notes: 'Got lost in Greenpath. Need to go back.',
    status: 'buried',
    moodTags: ['atmospheric', 'intense'],
    description: 'Forge your own path in Hollow Knight! An epic action-adventure through a vast, ruined kingdom of insects and heroes.',
    hltbMain: 27,
    hltbComplete: 63,
    enrichedAt: now,
    addedAt: daysAgo(150),
    updatedAt: daysAgo(130),
  },
  {
    id: sampleId(),
    name: 'Sekiro: Shadows Die Twice',
    source: 'steam',
    steamAppId: 814380,
    coverUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/814380/header.jpg',
    metacritic: 90,
    genres: ['Action', 'Adventure'],
    hoursPlayed: 0,
    installed: false,
    timeTier: 'marathon',
    category: 'The Pile',
    vibes: ['challenge'],
    priority: 2,
    notes: '',
    status: 'buried',
    moodTags: ['intense'],
    description: 'Carve your own clever path to vengeance in an all-new adventure from FromSoftware.',
    hltbMain: 30,
    hltbComplete: 72,
    enrichedAt: now,
    addedAt: daysAgo(300),
    updatedAt: daysAgo(300),
  },
  {
    id: sampleId(),
    name: 'Subnautica',
    source: 'steam',
    steamAppId: 264710,
    coverUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/264710/header.jpg',
    metacritic: 87,
    genres: ['Adventure', 'Survival', 'Indie'],
    hoursPlayed: 0,
    installed: false,
    timeTier: 'deep-cut',
    category: 'The Pile',
    vibes: ['atmospheric'],
    priority: 3,
    notes: '',
    status: 'buried',
    moodTags: ['atmospheric', 'spooky', 'creative'],
    description: 'Descend into the depths of an alien underwater world filled with wonder and peril.',
    hltbMain: 29,
    hltbComplete: 56,
    enrichedAt: now,
    addedAt: daysAgo(400),
    updatedAt: daysAgo(400),
  },
  {
    id: sampleId(),
    name: 'Ori and the Will of the Wisps',
    source: 'steam',
    steamAppId: 1057090,
    coverUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/1057090/header.jpg',
    metacritic: 88,
    genres: ['Platformer', 'Action', 'Adventure'],
    hoursPlayed: 0,
    installed: false,
    timeTier: 'deep-cut',
    category: 'The Pile',
    vibes: ['atmospheric', 'cozy'],
    priority: 4,
    notes: 'Loved the first one. This has been sitting here forever.',
    status: 'buried',
    moodTags: ['emotional', 'atmospheric'],
    description: 'The little spirit Ori is no stranger to peril, but when a fateful flight puts the owlet Ku in harm\'s way, every ounce of bravery is needed.',
    hltbMain: 11,
    hltbComplete: 20,
    enrichedAt: now,
    addedAt: daysAgo(500),
    updatedAt: daysAgo(500),
  },
  {
    id: sampleId(),
    name: 'Slay the Spire',
    source: 'steam',
    steamAppId: 646570,
    coverUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/646570/header.jpg',
    metacritic: 89,
    genres: ['Card Game', 'Strategy', 'Indie'],
    hoursPlayed: 0,
    installed: false,
    timeTier: 'wind-down',
    category: 'The Pile',
    vibes: [],
    priority: 5,
    notes: '',
    status: 'buried',
    moodTags: ['strategic', 'chill'],
    description: 'Craft a unique deck, encounter bizarre creatures, discover relics of immense power.',
    hltbMain: 28,
    hltbComplete: 303,
    enrichedAt: now,
    isNonFinishable: true,
    addedAt: daysAgo(200),
    updatedAt: daysAgo(200),
  },
  {
    id: sampleId(),
    name: 'Resident Evil Village',
    source: 'steam',
    steamAppId: 1196590,
    coverUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/1196590/header.jpg',
    metacritic: 84,
    genres: ['Horror', 'Action', 'Adventure'],
    hoursPlayed: 0,
    installed: false,
    timeTier: 'deep-cut',
    category: 'The Pile',
    vibes: [],
    priority: 6,
    notes: 'Tall lady.',
    status: 'buried',
    moodTags: ['spooky', 'intense'],
    description: 'Experience survival horror like never before in Resident Evil Village.',
    hltbMain: 10,
    hltbComplete: 32,
    enrichedAt: now,
    addedAt: daysAgo(350),
    updatedAt: daysAgo(350),
  },
  {
    id: sampleId(),
    name: 'Divinity: Original Sin 2',
    source: 'steam',
    steamAppId: 435150,
    coverUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/435150/header.jpg',
    metacritic: 93,
    genres: ['RPG', 'Strategy', 'Adventure'],
    hoursPlayed: 4,
    installed: false,
    timeTier: 'marathon',
    category: 'The Pile',
    vibes: ['narrative'],
    priority: 7,
    notes: 'Started co-op, friend stopped playing. Classic.',
    status: 'buried',
    moodTags: ['strategic', 'story-rich'],
    description: 'The critically acclaimed RPG that raised the bar for the genre.',
    hltbMain: 59,
    hltbComplete: 150,
    enrichedAt: now,
    addedAt: daysAgo(600),
    updatedAt: daysAgo(550),
  },
  {
    id: sampleId(),
    name: 'It Takes Two',
    source: 'steam',
    steamAppId: 1426210,
    coverUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/1426210/header.jpg',
    metacritic: 88,
    genres: ['Adventure', 'Action', 'Platformer'],
    hoursPlayed: 0,
    installed: false,
    timeTier: 'deep-cut',
    category: 'The Pile',
    vibes: ['cozy'],
    priority: 8,
    notes: 'Need a co-op partner first.',
    status: 'buried',
    moodTags: ['chill', 'creative'],
    description: 'Embark on the craziest journey of your life in It Takes Two, a genre-bending platform adventure.',
    hltbMain: 12,
    hltbComplete: 15,
    enrichedAt: now,
    addedAt: daysAgo(180),
    updatedAt: daysAgo(180),
  },
  {
    id: sampleId(),
    name: 'Returnal',
    source: 'playstation',
    coverUrl: 'https://media.rawg.io/media/games/af7/af7a831001c5c32c46e950cc883c7972.jpg',
    metacritic: 86,
    genres: ['Action', 'Shooter', 'Adventure'],
    hoursPlayed: 0,
    installed: false,
    timeTier: 'deep-cut',
    category: 'The Pile',
    vibes: ['challenge'],
    priority: 9,
    notes: '',
    status: 'buried',
    moodTags: ['intense', 'atmospheric'],
    description: 'Break the cycle of chaos on an always-changing alien planet.',
    hltbMain: 18,
    hltbComplete: 40,
    enrichedAt: now,
    addedAt: daysAgo(300),
    updatedAt: daysAgo(300),
  },
  {
    id: sampleId(),
    name: 'Tunic',
    source: 'steam',
    steamAppId: 553420,
    coverUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/553420/header.jpg',
    metacritic: 85,
    genres: ['Action', 'Adventure', 'Indie'],
    hoursPlayed: 0,
    installed: false,
    timeTier: 'deep-cut',
    category: 'The Pile',
    vibes: ['atmospheric'],
    priority: 10,
    notes: 'Zelda-like with secrets? Yes please.',
    status: 'buried',
    moodTags: ['atmospheric', 'strategic'],
    description: 'Explore a land filled with lost legends, ancient powers, and ferocious monsters.',
    hltbMain: 12,
    hltbComplete: 20,
    enrichedAt: now,
    addedAt: daysAgo(250),
    updatedAt: daysAgo(250),
  },
  {
    id: sampleId(),
    name: 'Unpacking',
    source: 'steam',
    steamAppId: 1135690,
    coverUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/1135690/header.jpg',
    metacritic: 80,
    genres: ['Puzzle', 'Casual', 'Indie'],
    hoursPlayed: 0,
    installed: false,
    timeTier: 'quick-hit',
    category: 'Quick Wins',
    vibes: ['cozy'],
    priority: 0,
    notes: 'Perfect for a chill evening.',
    status: 'buried',
    moodTags: ['chill', 'emotional'],
    description: 'The zen of unpacking a life. A meditative experience about the familiar and soothing act of pulling possessions out of boxes.',
    hltbMain: 3,
    hltbComplete: 5,
    enrichedAt: now,
    addedAt: daysAgo(100),
    updatedAt: daysAgo(100),
  },
  {
    id: sampleId(),
    name: 'The Talos Principle',
    source: 'steam',
    steamAppId: 257510,
    coverUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/257510/header.jpg',
    metacritic: 85,
    genres: ['Puzzle', 'Adventure'],
    hoursPlayed: 0,
    installed: false,
    timeTier: 'deep-cut',
    category: 'The Pile',
    vibes: ['philosophical', 'atmospheric'],
    priority: 11,
    notes: '',
    status: 'buried',
    moodTags: ['strategic', 'atmospheric'],
    description: 'A philosophical first-person puzzle game from the creators of Serious Sam.',
    hltbMain: 15,
    hltbComplete: 24,
    enrichedAt: now,
    addedAt: daysAgo(700),
    updatedAt: daysAgo(700),
  },
  {
    id: sampleId(),
    name: 'Psychonauts 2',
    source: 'xbox',
    coverUrl: 'https://media.rawg.io/media/games/0c5/0c5aea5a38bc574a5b6be8d2a9511385.jpg',
    metacritic: 87,
    genres: ['Platformer', 'Adventure', 'Action'],
    hoursPlayed: 0,
    installed: false,
    timeTier: 'deep-cut',
    category: 'The Pile',
    vibes: ['narrative'],
    priority: 12,
    notes: 'On Game Pass. Heard it\'s great.',
    status: 'buried',
    moodTags: ['story-rich', 'creative'],
    description: 'Razputin Aquato is working hard to earn his place among the Psychonauts.',
    hltbMain: 15,
    hltbComplete: 25,
    enrichedAt: now,
    addedAt: daysAgo(200),
    updatedAt: daysAgo(200),
  },
  {
    id: sampleId(),
    name: 'Neon White',
    source: 'steam',
    steamAppId: 1533420,
    coverUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/1533420/header.jpg',
    metacritic: 88,
    genres: ['Action', 'Platformer', 'Indie'],
    hoursPlayed: 0,
    installed: false,
    timeTier: 'wind-down',
    category: 'Quick Wins',
    vibes: ['challenge'],
    priority: 1,
    notes: 'Speed run heaven. Perfect for short bursts.',
    status: 'buried',
    moodTags: ['intense', 'competitive'],
    description: 'A lightning-fast first-person action game about slaying demons in Heaven.',
    hltbMain: 8,
    hltbComplete: 24,
    enrichedAt: now,
    addedAt: daysAgo(150),
    updatedAt: daysAgo(150),
  },
  {
    id: sampleId(),
    name: 'Persona 5 Royal',
    source: 'steam',
    steamAppId: 1687950,
    coverUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/1687950/header.jpg',
    metacritic: 95,
    genres: ['RPG', 'Adventure'],
    hoursPlayed: 0,
    installed: false,
    timeTier: 'marathon',
    category: 'The Pile',
    vibes: ['narrative'],
    priority: 13,
    notes: '100+ hours. When will I ever have time for this?',
    status: 'buried',
    moodTags: ['story-rich', 'strategic', 'emotional'],
    description: 'Don the mask of Joker and unite with your friends to steal the hearts of the corrupt.',
    hltbMain: 101,
    hltbComplete: 143,
    enrichedAt: now,
    addedAt: daysAgo(250),
    updatedAt: daysAgo(250),
  },
  {
    id: sampleId(),
    name: 'Shovel Knight',
    source: 'switch',
    coverUrl: 'https://media.rawg.io/media/games/f89/f89e0fba00e0b2ab83e08f3e3b2e9731.jpg',
    metacritic: 85,
    genres: ['Platformer', 'Action', 'Indie'],
    hoursPlayed: 0,
    installed: false,
    timeTier: 'wind-down',
    category: 'The Pile',
    vibes: ['challenge'],
    priority: 14,
    notes: '',
    status: 'buried',
    moodTags: ['intense', 'chill'],
    description: 'Shovel Knight is a sweeping classic action-adventure game with awesome gameplay, memorable characters, and an amazing chiptune soundtrack.',
    hltbMain: 6,
    hltbComplete: 15,
    enrichedAt: now,
    addedAt: daysAgo(500),
    updatedAt: daysAgo(500),
  },
  {
    id: sampleId(),
    name: 'SOMA',
    source: 'steam',
    steamAppId: 282140,
    coverUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/282140/header.jpg',
    metacritic: 84,
    genres: ['Horror', 'Adventure', 'Indie'],
    hoursPlayed: 0,
    installed: false,
    timeTier: 'deep-cut',
    category: 'The Pile',
    vibes: ['atmospheric', 'philosophical'],
    priority: 15,
    notes: 'Sci-fi horror. Need the right mood for this one.',
    status: 'buried',
    moodTags: ['spooky', 'atmospheric', 'emotional'],
    description: 'SOMA is a sci-fi horror game from the creators of Amnesia: The Dark Descent.',
    hltbMain: 9,
    hltbComplete: 12,
    enrichedAt: now,
    addedAt: daysAgo(600),
    updatedAt: daysAgo(600),
  },
  {
    id: sampleId(),
    name: 'Vampire Survivors',
    source: 'steam',
    steamAppId: 1794680,
    coverUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/1794680/header.jpg',
    metacritic: 86,
    genres: ['Action', 'Indie', 'Casual'],
    hoursPlayed: 0,
    installed: false,
    timeTier: 'quick-hit',
    category: 'Quick Wins',
    vibes: ['mindless'],
    priority: 2,
    notes: 'Perfect brain-off game.',
    status: 'buried',
    moodTags: ['brainless', 'chill'],
    description: 'Mow down thousands of night creatures and survive until dawn!',
    hltbMain: 8,
    hltbComplete: 35,
    enrichedAt: now,
    isNonFinishable: true,
    addedAt: daysAgo(180),
    updatedAt: daysAgo(180),
  },
  {
    id: sampleId(),
    name: 'God of War (2018)',
    source: 'steam',
    steamAppId: 1593500,
    coverUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/1593500/header.jpg',
    metacritic: 93,
    genres: ['Action', 'Adventure', 'RPG'],
    hoursPlayed: 0,
    installed: false,
    timeTier: 'marathon',
    category: 'The Pile',
    vibes: ['narrative'],
    priority: 16,
    notes: 'BOY!',
    status: 'buried',
    moodTags: ['intense', 'story-rich', 'emotional'],
    description: 'Kratos is a father again. As mentor and protector to Atreus, a son determined to earn his respect.',
    hltbMain: 21,
    hltbComplete: 51,
    enrichedAt: now,
    addedAt: daysAgo(200),
    updatedAt: daysAgo(200),
  },
  {
    id: sampleId(),
    name: 'Factorio',
    source: 'steam',
    steamAppId: 427520,
    coverUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/427520/header.jpg',
    metacritic: 90,
    genres: ['Strategy', 'Simulation', 'Indie'],
    hoursPlayed: 0,
    installed: false,
    timeTier: 'marathon',
    category: 'The Pile',
    vibes: [],
    priority: 17,
    notes: 'I\'m scared to start this.',
    status: 'buried',
    moodTags: ['strategic', 'creative'],
    description: 'Build and maintain factories. Automate everything.',
    hltbMain: 92,
    hltbComplete: 300,
    enrichedAt: now,
    isNonFinishable: true,
    addedAt: daysAgo(400),
    updatedAt: daysAgo(400),
  },
  {
    id: sampleId(),
    name: 'A Short Hike',
    source: 'steam',
    steamAppId: 1055540,
    coverUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/1055540/header.jpg',
    metacritic: 83,
    genres: ['Adventure', 'Indie', 'Casual'],
    hoursPlayed: 0,
    installed: false,
    timeTier: 'quick-hit',
    category: 'Quick Wins',
    vibes: ['cozy'],
    priority: 3,
    notes: 'Takes like 2 hours. Just play it already.',
    status: 'buried',
    moodTags: ['chill', 'emotional'],
    description: 'Hike, climb, and soar through the peaks of Hawk Peak Provincial Park.',
    hltbMain: 2,
    hltbComplete: 3,
    enrichedAt: now,
    addedAt: daysAgo(300),
    updatedAt: daysAgo(300),
  },
  {
    id: sampleId(),
    name: 'Titanfall 2',
    source: 'steam',
    steamAppId: 1237970,
    coverUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/1237970/header.jpg',
    metacritic: 89,
    genres: ['Action', 'Shooter'],
    hoursPlayed: 0,
    installed: false,
    timeTier: 'wind-down',
    category: 'The Pile',
    vibes: [],
    priority: 18,
    notes: 'Campaign is supposed to be incredible.',
    status: 'buried',
    moodTags: ['intense', 'emotional'],
    description: 'Call down your Titan and get ready to fight in an exciting single player campaign.',
    hltbMain: 6,
    hltbComplete: 14,
    enrichedAt: now,
    addedAt: daysAgo(350),
    updatedAt: daysAgo(350),
  },
  {
    id: sampleId(),
    name: 'Darkest Dungeon',
    source: 'steam',
    steamAppId: 262060,
    coverUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/262060/header.jpg',
    metacritic: 84,
    genres: ['RPG', 'Strategy', 'Indie'],
    hoursPlayed: 3,
    installed: false,
    timeTier: 'deep-cut',
    category: 'The Pile',
    vibes: ['challenge', 'atmospheric'],
    priority: 19,
    notes: 'First dungeon killed my whole party. Shelved it.',
    status: 'buried',
    moodTags: ['intense', 'spooky', 'strategic'],
    description: 'Darkest Dungeon is a challenging gothic roguelike turn-based RPG about the psychological stresses of adventuring.',
    hltbMain: 57,
    hltbComplete: 100,
    enrichedAt: now,
    addedAt: daysAgo(400),
    updatedAt: daysAgo(380),
  },
  {
    id: sampleId(),
    name: 'Cocoon',
    source: 'steam',
    steamAppId: 1497440,
    coverUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/1497440/header.jpg',
    metacritic: 88,
    genres: ['Puzzle', 'Adventure', 'Indie'],
    hoursPlayed: 0,
    installed: false,
    timeTier: 'wind-down',
    category: 'Quick Wins',
    vibes: ['atmospheric'],
    priority: 4,
    notes: 'From the Limbo/Inside designer. Looks gorgeous.',
    status: 'buried',
    moodTags: ['atmospheric', 'chill'],
    description: 'A unique puzzle adventure where each world exists within an orb you carry on your back.',
    hltbMain: 5,
    hltbComplete: 7,
    enrichedAt: now,
    addedAt: daysAgo(100),
    updatedAt: daysAgo(100),
  },
  {
    id: sampleId(),
    name: 'Hades II',
    source: 'steam',
    steamAppId: 1145350,
    coverUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/1145350/header.jpg',
    metacritic: 88,
    genres: ['Action', 'Indie', 'RPG'],
    hoursPlayed: 0,
    installed: false,
    timeTier: 'deep-cut',
    category: 'The Pile',
    vibes: ['challenge'],
    priority: 20,
    notes: 'Early access. Waiting? Playing? Who knows.',
    status: 'buried',
    isWishlisted: true,
    moodTags: ['intense', 'story-rich'],
    description: 'Battle beyond the Underworld using the full might of Olympus in the bewitching sequel to Hades.',
    hltbMain: 25,
    hltbComplete: 80,
    enrichedAt: now,
    addedAt: daysAgo(50),
    updatedAt: daysAgo(50),
  },
  {
    id: sampleId(),
    name: 'Animal Well',
    source: 'steam',
    steamAppId: 813230,
    coverUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/813230/header.jpg',
    metacritic: 91,
    genres: ['Puzzle', 'Platformer', 'Indie'],
    hoursPlayed: 0,
    installed: false,
    timeTier: 'wind-down',
    category: 'The Pile',
    vibes: ['atmospheric'],
    priority: 21,
    notes: 'Supposed to have crazy secrets.',
    status: 'buried',
    isWishlisted: true,
    moodTags: ['atmospheric', 'spooky'],
    description: 'A densely detailed labyrinthine world to explore. Hatch from your flower and find your way.',
    hltbMain: 8,
    hltbComplete: 25,
    enrichedAt: now,
    addedAt: daysAgo(30),
    updatedAt: daysAgo(30),
  },
];
