import { Game } from './types';
import { v4 as uuidv4 } from 'uuid';

/**
 * Dev seed data — pre-populated games for testing interactions.
 * Only loaded when localStorage is empty and NODE_ENV === 'development'.
 */

const now = new Date().toISOString();
const daysAgo = (d: number) => new Date(Date.now() - d * 86400000).toISOString();

export const SEED_GAMES: Game[] = [
  // Now Playing
  {
    id: uuidv4(),
    name: 'Baldur\'s Gate 3',
    source: 'steam',
    steamAppId: 1086940,
    coverUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/1086940/header.jpg',
    metacritic: 96,
    genres: ['RPG', 'Adventure', 'Strategy'],
    hoursPlayed: 47,
    installed: true,
    timeTier: 'marathon',
    category: 'The Pile',
    vibes: [],
    priority: 0,
    notes: '47h on Steam. Deep in Act 2.',
    status: 'playing',
    moodTags: ['story-rich', 'strategic'],
    description: 'Gather your party and return to the Forgotten Realms in a tale of fellowship and betrayal, sacrifice and survival.',
    hltbMain: 55,
    hltbComplete: 150,
    enrichedAt: now,
    addedAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },

  // Play Next (on-deck)
  {
    id: uuidv4(),
    name: 'Hades',
    source: 'steam',
    steamAppId: 1145360,
    coverUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/1145360/header.jpg',
    metacritic: 93,
    genres: ['Action', 'Indie', 'RPG'],
    hoursPlayed: 2,
    installed: true,
    timeTier: 'deep-cut',
    category: 'The Pile',
    vibes: [],
    priority: 0,
    notes: '2h on Steam',
    status: 'on-deck',
    moodTags: ['intense', 'story-rich'],
    description: 'Defy the god of the dead as you hack and slash your way out of the Underworld in this rogue-like dungeon crawler.',
    hltbMain: 21,
    hltbComplete: 96,
    enrichedAt: now,
    addedAt: daysAgo(60),
    updatedAt: daysAgo(5),
  },
  {
    id: uuidv4(),
    name: 'Celeste',
    source: 'steam',
    steamAppId: 504230,
    coverUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/504230/header.jpg',
    metacritic: 92,
    genres: ['Platformer', 'Indie'],
    hoursPlayed: 0,
    installed: false,
    timeTier: 'wind-down',
    category: 'Quick Wins',
    vibes: [],
    priority: 1,
    notes: '',
    status: 'on-deck',
    moodTags: ['intense', 'emotional'],
    description: 'Help Madeline survive her inner demons on her journey to the top of Celeste Mountain.',
    hltbMain: 8,
    hltbComplete: 36,
    enrichedAt: now,
    addedAt: daysAgo(90),
    updatedAt: daysAgo(10),
  },

  // Backlog — enriched
  {
    id: uuidv4(),
    name: 'Disco Elysium - The Final Cut',
    source: 'steam',
    steamAppId: 632470,
    coverUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/632470/header.jpg',
    metacritic: 97,
    genres: ['RPG', 'Adventure'],
    hoursPlayed: 0,
    installed: false,
    timeTier: 'deep-cut',
    category: 'The Pile',
    vibes: [],
    priority: 2,
    notes: '',
    status: 'buried',
    moodTags: ['story-rich', 'atmospheric'],
    description: 'A groundbreaking open-world RPG about being a cop in a city on the brink. Question suspects, explore, or just get hammered.',
    hltbMain: 30,
    hltbComplete: 53,
    enrichedAt: now,
    addedAt: daysAgo(365),
    updatedAt: daysAgo(365),
  },
  {
    id: uuidv4(),
    name: 'Hollow Knight',
    source: 'steam',
    steamAppId: 367520,
    coverUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/367520/header.jpg',
    metacritic: 87,
    genres: ['Action', 'Adventure', 'Indie'],
    hoursPlayed: 3,
    installed: true,
    timeTier: 'deep-cut',
    category: 'The Pile',
    vibes: [],
    priority: 3,
    notes: '3h on Steam. Got lost in Greenpath.',
    status: 'buried',
    moodTags: ['atmospheric', 'intense'],
    description: 'Forge your own path in Hollow Knight! An epic action adventure through a vast, ruined kingdom of insects and heroes.',
    hltbMain: 26,
    hltbComplete: 63,
    enrichedAt: now,
    addedAt: daysAgo(200),
    updatedAt: daysAgo(180),
  },
  {
    id: uuidv4(),
    name: 'Stardew Valley',
    source: 'steam',
    steamAppId: 413150,
    coverUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/413150/header.jpg',
    metacritic: 89,
    genres: ['Simulation', 'RPG', 'Indie'],
    hoursPlayed: 142,
    installed: true,
    timeTier: 'marathon',
    category: 'Favorites',
    vibes: [],
    priority: 0,
    notes: '142h on Steam',
    status: 'buried',
    moodTags: ['chill', 'creative'],
    description: 'Build the farm of your dreams. Raise animals, grow crops, start an orchard, and make friends.',
    hltbMain: 52,
    hltbComplete: 152,
    enrichedAt: now,
    addedAt: daysAgo(500),
    updatedAt: daysAgo(30),
  },
  {
    id: uuidv4(),
    name: 'Outer Wilds',
    source: 'steam',
    steamAppId: 753640,
    coverUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/753640/header.jpg',
    metacritic: 85,
    genres: ['Adventure', 'Indie'],
    hoursPlayed: 0,
    installed: false,
    timeTier: 'deep-cut',
    category: 'The Pile',
    vibes: [],
    priority: 4,
    notes: '',
    status: 'buried',
    moodTags: ['atmospheric', 'story-rich'],
    description: 'An open world mystery about a solar system trapped in an endless time loop. Best experienced knowing nothing.',
    hltbMain: 15,
    hltbComplete: 22,
    enrichedAt: now,
    addedAt: daysAgo(400),
    updatedAt: daysAgo(400),
  },
  {
    id: uuidv4(),
    name: 'Portal 2',
    source: 'steam',
    steamAppId: 620,
    coverUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/620/header.jpg',
    metacritic: 95,
    genres: ['Puzzle', 'Action'],
    hoursPlayed: 0,
    installed: false,
    timeTier: 'wind-down',
    category: 'Quick Wins',
    vibes: [],
    priority: 5,
    notes: '',
    status: 'buried',
    moodTags: ['brainless', 'chill'],
    description: 'The highly anticipated sequel to the award-winning Portal. Featuring co-op and a hilarious single-player campaign.',
    hltbMain: 8,
    hltbComplete: 19,
    enrichedAt: now,
    addedAt: daysAgo(1000),
    updatedAt: daysAgo(1000),
  },

  // Backlog — unenriched (to test auto-enrichment indicator)
  {
    id: uuidv4(),
    name: 'Slay the Spire',
    source: 'steam',
    steamAppId: 646570,
    coverUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/646570/header.jpg',
    metacritic: 89,
    genres: [],
    hoursPlayed: 0,
    installed: false,
    timeTier: 'wind-down',
    category: 'The Pile',
    vibes: [],
    priority: 6,
    notes: '',
    status: 'buried',
    addedAt: daysAgo(150),
    updatedAt: daysAgo(150),
  },
  {
    id: uuidv4(),
    name: 'Dead Cells',
    source: 'steam',
    steamAppId: 588650,
    coverUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/588650/header.jpg',
    genres: [],
    hoursPlayed: 1,
    installed: false,
    timeTier: 'wind-down',
    category: 'The Pile',
    vibes: [],
    priority: 7,
    notes: '1h on Steam',
    status: 'buried',
    addedAt: daysAgo(250),
    updatedAt: daysAgo(250),
  },

  // Cleared games
  {
    id: uuidv4(),
    name: 'The Witcher 3: Wild Hunt',
    source: 'steam',
    steamAppId: 292030,
    coverUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/292030/header.jpg',
    metacritic: 92,
    genres: ['RPG', 'Adventure'],
    hoursPlayed: 120,
    installed: false,
    timeTier: 'marathon',
    category: 'The Pile',
    vibes: [],
    priority: 8,
    notes: '120h on Steam',
    status: 'played',
    rating: 5,
    completedAt: daysAgo(60),
    moodTags: ['story-rich', 'atmospheric'],
    description: 'A story-driven open world RPG set in a visually stunning fantasy universe full of meaningful choices.',
    hltbMain: 51,
    hltbComplete: 172,
    enrichedAt: now,
    addedAt: daysAgo(700),
    updatedAt: daysAgo(60),
  },
  {
    id: uuidv4(),
    name: 'Undertale',
    source: 'steam',
    steamAppId: 391540,
    coverUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/391540/header.jpg',
    metacritic: 92,
    genres: ['RPG', 'Indie'],
    hoursPlayed: 8,
    installed: false,
    timeTier: 'wind-down',
    category: 'The Pile',
    vibes: [],
    priority: 9,
    notes: '',
    status: 'played',
    rating: 4,
    completedAt: daysAgo(120),
    moodTags: ['story-rich', 'emotional'],
    description: 'A small child falls into the Underground, a large, secluded region underneath the surface of the Earth.',
    hltbMain: 7,
    hltbComplete: 21,
    enrichedAt: now,
    addedAt: daysAgo(800),
    updatedAt: daysAgo(120),
  },

  // Bailed game
  {
    id: uuidv4(),
    name: 'Elden Ring',
    source: 'steam',
    steamAppId: 1245620,
    coverUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/1245620/header.jpg',
    metacritic: 96,
    genres: ['Action', 'RPG'],
    hoursPlayed: 15,
    installed: false,
    timeTier: 'marathon',
    category: 'The Pile',
    vibes: [],
    priority: 10,
    notes: '15h on Steam. Margit broke me.',
    status: 'bailed',
    moodTags: ['intense', 'atmospheric'],
    description: 'An action RPG developed by FromSoftware and produced in collaboration with George R.R. Martin.',
    hltbMain: 55,
    hltbComplete: 132,
    enrichedAt: now,
    addedAt: daysAgo(300),
    updatedAt: daysAgo(100),
  },

  // Wishlisted game
  {
    id: uuidv4(),
    name: 'Silksong',
    source: 'steam',
    coverUrl: undefined,
    genres: ['Action', 'Adventure', 'Indie'],
    hoursPlayed: 0,
    installed: false,
    timeTier: 'deep-cut',
    category: 'The Pile',
    vibes: [],
    priority: 11,
    notes: '',
    status: 'buried',
    isWishlisted: true,
    moodTags: ['atmospheric', 'intense'],
    description: 'The sequel to Hollow Knight. Play as Hornet in a haunting new kingdom.',
    hltbMain: undefined,
    enrichedAt: now,
    addedAt: daysAgo(500),
    updatedAt: daysAgo(500),
  },

  // PlayStation game
  {
    id: uuidv4(),
    name: 'God of War Ragnarok',
    source: 'playstation',
    coverUrl: 'https://image.api.playstation.com/vulcan/ap/rnd/202207/1210/4xJ8XB3bi888QTLZYdqbO8z2.png',
    metacritic: 94,
    genres: ['Action', 'Adventure'],
    hoursPlayed: 0,
    installed: false,
    timeTier: 'deep-cut',
    category: 'The Pile',
    vibes: [],
    priority: 12,
    notes: 'PS5',
    status: 'buried',
    moodTags: ['intense', 'story-rich'],
    description: 'Kratos and Atreus embark on a mythic journey for answers before the prophesied Ragnarok arrives.',
    hltbMain: 26,
    hltbComplete: 53,
    enrichedAt: now,
    addedAt: daysAgo(180),
    updatedAt: daysAgo(180),
  },
];
